parameters:
#    gestion_yamaha.example.class: Gestion\YamahaBundle\Example

services:
#    gestion_yamaha.example:
#        class: %gestion_yamaha.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
