<?php

namespace Gestion\YamahaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleRepository extends EntityRepository
{
}
