<?php

namespace Gestion\YamahaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{

    public function recherche($chaine){

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id like :chaine')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        return $qb->getQuery()->getResult();
    }
}
