<?php

namespace Gestion\YamahaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function checkUser($username, $password){

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.username = :username ')
            ->andWhere('u.password = :password')
            ->setParameters(array(
                'username' => $username,
                'password' => $password
            ));

        return $qb->getQuery()->getResult();
    }

    public function getDefaultOptions()
    {
        return array(
            'data_class' => 'Gestion\YamahaBundle\Entity\User',
            'id'         => null
        );
    }

}
